# Site settings
baseurl = "http://juliagreig.github.io"
languageCode = "en-us"
title = "Julia Greig"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Julia Greig"
	description = "doin cool things"
	bio = "i do computer stuff and startup stuff <br> and art stuff and yoga stuff"
	# Enter optionally your twitter account
	twitter = "@julia_greig"
	enableRSS = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	blog = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a cool gal"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	# iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  #  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/julia_greig/"
    linkedin = "https://ca.linkedin.com/in/juliagreig/"
    github   = "https://github.com/juliagreig/"
		8tracks	 = "http://8tracks.com/jul1a"
		instagram = "https://www.instagram.com/julia.greig/"
		blog = "/about"
